# Generated by Django 3.1 on 2020-08-20 07:31

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dish_name', models.CharField(max_length=200, verbose_name='Name of Dish')),
                ('Desc', models.TextField(verbose_name='Dish Description')),
                ('Amount', models.IntegerField(verbose_name='Amount of Dish')),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Dish Date Posted')),
                ('category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='food.category')),
            ],
        ),
    ]
