# Generated by Django 3.1 on 2020-08-20 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading_main', models.CharField(max_length=200, verbose_name='Main Heading')),
                ('main_desc', models.TextField(verbose_name='Main Description')),
                ('sub_heading', models.CharField(max_length=200, verbose_name='Sub Heading')),
                ('sub_desc', models.TextField(verbose_name='Sub Description')),
            ],
        ),
    ]
