# Generated by Django 3.1 on 2020-08-20 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0004_gallery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='about_heading',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Tag line in Image'),
        ),
    ]
