# Generated by Django 3.1 on 2020-08-21 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0005_auto_20200820_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='about_heading',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Tag line in Image'),
        ),
    ]
