# Generated by Django 3.1 on 2020-08-21 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0006_auto_20200821_1155'),
    ]

    operations = [
        migrations.CreateModel(
            name='Headings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_heading', models.CharField(blank=True, max_length=200, null=True, verbose_name='Tag line in About Page')),
                ('menu_heading', models.CharField(blank=True, max_length=200, null=True, verbose_name='Tag line in Menu Page')),
                ('gallery_heading', models.CharField(blank=True, max_length=200, null=True, verbose_name='Tag line in Gallery Page')),
            ],
        ),
        migrations.RemoveField(
            model_name='about',
            name='about_heading',
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='about_heading',
        ),
    ]
