# Generated by Django 3.1 on 2020-08-21 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0008_auto_20200821_1233'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_main', models.CharField(max_length=200, verbose_name='Address Main')),
                ('address_sub', models.CharField(max_length=200, verbose_name='Address Sub')),
                ('weekday_opening', models.CharField(max_length=200, verbose_name='Weekday Opening Hours')),
                ('weekend_opening', models.CharField(max_length=200, verbose_name='Weekend Opening Hours')),
                ('phone', models.IntegerField(help_text='Enter Phone Number Like +91-##########', max_length=13, verbose_name='Phone number')),
                ('email', models.CharField(max_length=200, verbose_name='Email')),
            ],
        ),
    ]
