# Generated by Django 3.1 on 2020-08-21 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0012_auto_20200821_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='Amount',
            field=models.CharField(max_length=10, verbose_name='Amount of Dish'),
        ),
    ]
