# Generated by Django 3.1 on 2020-08-22 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0013_auto_20200821_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactdetails',
            name='phone',
            field=models.CharField(help_text='Enter Phone Number Like +91-##########', max_length=15, verbose_name='Phone number'),
        ),
    ]
