# Generated by Django 3.1 on 2020-08-22 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0014_auto_20200822_1154'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('msg_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('desc', models.TextField(max_length=500)),
            ],
        ),
    ]
