# Generated by Django 3.1 on 2020-08-25 06:28

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0015_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='heading_main',
            field=models.CharField(help_text='Enter the Main Heading to be displayed ', max_length=200, verbose_name='Main Heading'),
        ),
        migrations.AlterField(
            model_name='about',
            name='img',
            field=models.ImageField(default='default.jpg', help_text='Select the Image and is Mandatory', upload_to='blog'),
        ),
        migrations.AlterField(
            model_name='about',
            name='main_desc',
            field=models.TextField(help_text='Enter the Main Description or the content', verbose_name='Main Description'),
        ),
        migrations.AlterField(
            model_name='about',
            name='sub_desc',
            field=models.TextField(help_text='Enter the Sub Description if any and is Mandatory', verbose_name='Sub Description'),
        ),
        migrations.AlterField(
            model_name='about',
            name='sub_heading',
            field=models.CharField(help_text='Enter the Sub Heading if any and is Mandatory', max_length=200, verbose_name='Sub Heading'),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(help_text='Enter the Category Name to be Displayed', max_length=50),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='dishname',
            field=models.CharField(help_text='Enter the Dish Name to be Displayed on Image', max_length=200, verbose_name='Dish Name for every picture'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='img',
            field=models.ImageField(default='default.jpg', help_text='Select the Image to be Displayed', upload_to='Gallery'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='Desc',
            field=models.TextField(help_text='Enter the Description of the Dish Name', verbose_name='Dish Description'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='category',
            field=models.ForeignKey(default=1, help_text='Please select the Category in which Dish needs to be Shown', on_delete=django.db.models.deletion.CASCADE, to='food.category'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Leave as it is', verbose_name='Dish Date Posted'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='dish_name',
            field=models.CharField(help_text='Enter the Dish Name to be Displayed', max_length=200, verbose_name='Name of Dish'),
        ),
    ]
